OCAMLMAKEFILE = OCamlMakefile

ANNOTATE = yes
export ANNOTATE
DEBUG = yes
export DEBUG

OCAMLRUNPARAM=b
export OCAMLRUNPARAM

USE_CAMLP4 := yes
SOURCES= client/ocaml/lifedb.ml custom_unix_stubs.c utils.ml lifedb_config.ml sql_access.ml log.ml \
	sql_mtype_map.ml sql_mirror.ml lifesql.ml
THREADS=yes
RESULT=lifesql
PACKS=unix json-static json-wheel sqlite3 str ANSITerminal
LIBDIRS=/opt/local/lib

PP=./camlp4find $(PACKS)
export PP

.PHONY: all
all: dnc
	@ :

include $(OCAMLMAKEFILE)
