OCAMLMAKEFILE = OCamlMakefile

ANNOTATE = yes
export ANNOTATE
DEBUG = yes
export DEBUG

OCAMLRUNPARAM=b
export OCAMLRUNPARAM

SOURCES=passwords.ml password_tests.ml
RESULT=passtest
PACKS=cryptokit ounit

.PHONY: all
all: dnc
	@ :

.PHONY: test
test: all
	./$(RESULT) -verbose

include $(OCAMLMAKEFILE)
